In [0]:
!pip install -U -q PyDrive ## you will have install for every colab session

from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials

# 1. Authenticate and create the PyDrive client.
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
!apt-get install -y -qq software-properties-common python-software-properties module-init-tools
!add-apt-repository -y ppa:alessandro-strada/ppa 2>&1 > /dev/null
!apt-get update -qq 2>&1 > /dev/null
!apt-get -y install -qq google-drive-ocamlfuse fuse
from google.colab import auth
auth.authenticate_user()
from oauth2client.client import GoogleCredentials
creds = GoogleCredentials.get_application_default()
import getpass
!google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret} < /dev/null 2>&1 | grep URL
vcode = getpass.getpass()
!echo {vcode} | google-drive-ocamlfuse -headless -id={creds.client_id} -secret={creds.client_secret}

gpg: keybox '/tmp/tmplsvqizm_/pubring.gpg' created
gpg: /tmp/tmplsvqizm_/trustdb.gpg: trustdb created
gpg: key AD5F235DF639B041: public key "Launchpad PPA for Alessandro Strada" imported
gpg: Total number processed: 1
gpg:               imported: 1
··········


In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option


In [0]:
!ls drive

20180606_151724.mp4
ACM ICPC.odt
Application overview.odt
BeeWare Essay.odt
BHU PROJECT.odt
CD Unit -1.pdf
cd unit 3.pdf
CD Unit - 4.pdf
CD Unit -5.pdf
Colab Notebooks
Companies.ods
Copy of Cover Letter.odt
Copy of Eshan's Resume.odt
Cover Letter.odt
DataScienceBookV3.pdf
Data Structure
DeepNeuralNetworks
Draft BeeWare.odt
Eshan's Resume.odt
ETicket
Genetic Algorithm.odt
GSoC Proposal to Aimacode for Aimacode_Python.odt
Java Traning Assignment 1 WelTec.odt
Java Traning Assignment 1 WelTec.odt (589ac6ea)
Paper.pdf
Power Point Presentation.pdf
resume_latest.pdf
Schol chle hm!!
Shiv Mandir
TechSmith
testModel.ipynb
this.mp4
TrainData
unit2 cd.pdf
Untitled document.odt
Untitled document.odt (2901b5d1)
Untitled document.odt (70918aa5)
Untitled document.odt (8c68fcee)
Untitled document.odt (a29b122a)
Untitled document.odt (bd14a30f)
Untitled document.odt (cdb95678)
Untitled document.odt (d25e2089)
Untitled document.odt (f447c082)
Untitled drawing.png
Untitled drawing.png (15fa0c46)
Untitled 

In [0]:
from google.colab import files

In [0]:
Folder = drive.CreateFile({'id':'1yQECTj2sE8Ra4BTv8CtD39H6tJ3KEzIl'})


In [0]:
type(Folder)

pydrive.files.GoogleDriveFile

In [0]:
!mkdir -p drive
!google-drive-ocamlfuse drive

fuse: mountpoint is not empty
fuse: if you are sure this is safe, use the 'nonempty' mount option


In [0]:
# import modules
import glob
import numpy as np
import cv2
from random import shuffle

# resize images    
for img in glob.iglob("TrainData/*.png"):
    im = cv2.imread(img)
    im_resize = cv2.resize(im,(50,50))
    cv2.imwrite(img, im_resize)
    
# Load image names in ramdom manner
image_list = [img for img in glob.iglob("TrainData/*.png")]
shuffle(image_list)

# Load Data
X_data = np.empty(shape=[len(image_list), 50, 50, 3])
Y_data = np.zeros((10160, 10))

i = 0
for image in image_list:
    X_data[i] = cv2.imread(image)
    index = int(image_list[i][15:16]) - 1
    Y_data[i][index] = 1
    i = i + 1
    
Y_data = Y_data.astype(int)

for i in range(len(Y_data)):
    for j in range(10):
        if Y_data[i,j] == -1:
            Y_data[i,j] = 9
X_data = X_data / 255


# len(image_list) = 10160
# training data
X_train = X_data[0:8000]
Y_train = Y_data[0:8000]

# test data
X_test = X_data[8000:10160]
Y_test = Y_data[8000:10160]

# import modules
from keras.models import Sequential
from keras.layers import Conv2D, MaxPooling2D
from keras.layers import Activation, Dropout, Flatten, Dense
from keras.layers.normalization import BatchNormalization
from keras import optimizers

model = Sequential()

model.add(Conv2D(32, (3, 3), input_shape=(50,50,3)))
model.add(Activation('relu'))
BatchNormalization(axis=-1)
model.add(Conv2D(32, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

BatchNormalization(axis=-1)
model.add(Conv2D(64,(3, 3)))
model.add(Activation('relu'))
BatchNormalization(axis=-1)
model.add(Conv2D(64, (3, 3)))
model.add(Activation('relu'))
model.add(MaxPooling2D(pool_size=(2,2)))

model.add(Flatten())
# Fully connected layer

BatchNormalization()
model.add(Dense(512))
model.add(Activation('relu'))
BatchNormalization()
model.add(Dropout(0.2))
model.add(Dense(10))

model.add(Activation('softmax'))

sgd = optimizers.SGD(lr=0.01, clipvalue=0.5)
model.compile(loss='mean_squared_error',
              optimizer=sgd,
              metrics=['accuracy'])


model.fit(X_train, Y_train,
          epochs=45,
          batch_size=10)

score = model.evaluate(X_test, Y_test, batch_size=32)
print("--------------------------------------------")
print("Score is",score)

# save weights
#model.save_weights('keras_digit_classifier.h5')

ValueError: ignored

In [0]:
import cv2

In [0]:
#https://drive.google.com/open?id=1JluuiEkzl5-xBUJck32qNUBJJgpqJLFI
image = drive.CreateFile({'id':'1JluuiEkzl5-xBUJck32qNUBJJgpqJLFI'})
image.GetContentFile('Screen Shot 2018-07-04 at 3.39.03 PM')
im = cv2.imread('Screen Shot 2018-07-04 at 3.39.03 PM')
print(im)

[[[ 48  45   1]
  [112 111  61]
  [143 143  79]
  ...
  [192 198 209]
  [192 198 209]
  [193 200 209]]

 [[ 47  44   0]
  [112 111  61]
  [144 144  80]
  ...
  [191 197 210]
  [191 197 208]
  [191 197 208]]

 [[ 47  44   0]
  [112 111  61]
  [145 145  81]
  ...
  [189 196 211]
  [188 196 209]
  [188 196 209]]

 ...

 [[ 44  35  15]
  [ 97  90  65]
  [125 120  87]
  ...
  [ 78  60  53]
  [ 79  61  54]
  [ 79  61  54]]

 [[ 11   3   0]
  [ 13   7   0]
  [ 16  12   0]
  ...
  [ 13   1   0]
  [ 13   1   0]
  [ 14   2   0]]

 [[  9   4   6]
  [  4   0   0]
  [  8   6   0]
  ...
  [  8   0   0]
  [  9   1   1]
  [  9   1   1]]]


In [0]:
!pwd drive

/content


In [0]:
#https://drive.google.com/open?id=1yQECTj2sE8Ra4BTv8CtD39H6tJ3KEzIl
Folder = drive.CreateFile({'id':'1yQECTj2sE8Ra4BTv8CtD39H6tJ3KEzIl'})

NameError: ignored